apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-index
data:
  index.html: |
    <html>
      <body style="background-color:blue; color:white;">
        <h1>BLUE version</h1>
      </body>
    </html>
