apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-green-demo
resources:
  - namespace.yaml
  - configmap-blue.yaml
  - configmap-green.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
